version: '3.8'

services:
  postgres:
    container_name: projetoteste
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=projetoteste